player playActionNow "GestureReset";
_weapon = primaryWeapon player;
_items = primaryWeaponItems player;
player removeweapon _weapon;
player removeMagazine "FLAY_1Rnd_RegularArrow";
player removeMagazine "FLAY_1Rnd_RegularArrow";
player removemagazine "FLAY_1Rnd_DummyArrow2";
player removemagazine "FLAY_1Rnd_DummyArrow2";
player removemagazine "FLAY_1Rnd_DummyArrow1";
player removemagazine "FLAY_1Rnd_DummyArrow1";
player addweapon _weapon;
{ player addPrimaryWeaponItem _x; } forEach _items;